FROM python:3.10-slim

WORKDIR /frontend

# Copy only what's needed
COPY app/frontend_ui_chainlit.py app/
COPY app/env.py app/
COPY requirements_frontend_chainlit.txt .

RUN pip install --no-cache-dir -r requirements_frontend_chainlit.txt

EXPOSE 8501

CMD ["chainlit", "run", "app/frontend_ui_chainlit.py", "--host=0.0.0.0", "--port=8501"]
